### ISSUE TITLE
Icon not showing for Mac

### ISSUE THREAD

**Issue by luandro** [digidem/mbtiles-asar-gui#2]
The icon for Mac isn't showing up. Need to investigate the correct folder and file naming for Electron.

**Comment by achou11** [comment]
think there's something wrong with the image asset you're using. i tried it with a different one and was able to get it to display:

<img width="200" alt="image" src="https://github.com/digidem/mbtiles-asar-gui/assets/18542095/c2ee2865-601a-4776-8b7e-34be81aa3085">

<img width="154" alt="image" src="https://github.com/digidem/mbtiles-asar-gui/assets/18542095/f3cc6921-8c8e-4c1f-a383-36d787de5f1d">
